package-lock.json
package.json
spec/openapi.yaml
ui/src/components/notification/welcome.tsx
ui/src/components/status-board/board.tsx
ui/src/components/telemetry/index.ts
ui/src/components/utils/index.ts

Replace remaining_time to time_est

Fix remaining time

---

fake_server/server.js
ui/src/components/status-board/board.tsx

Use UTC date with timezone from printer

---

ui/src/components/notification/welcome.tsx
ui/src/routes/home/index.tsx

Reverts prusa3d/Prusa-Connect-Local#24

Revert "add show-welcome url argument for displays without input"

---

ui/src/components/app.tsx
ui/src/components/header/index.tsx

Fixed wrong indexOf condition, add saving changes language into a Local Storage

Add localStorage & condition bugfix

---

package-lock.json
package.json
ui/src/components/app.tsx
ui/src/components/container.tsx
ui/src/components/header/index.tsx
ui/src/components/header/style.scss
ui/src/i18n/cs.json
ui/src/i18n/de.json
ui/src/i18n/en.json
ui/src/i18n/es.json
ui/src/i18n/fr.json
ui/src/i18n/it.json
ui/src/i18n/pl.json
webpack.config.js

add change language

---

package-lock.json
package.json
scripts/remote_web_install.sh
ui/src/components/apikey/index.tsx
ui/src/components/app.tsx
ui/src/components/errors/index.tsx
ui/src/components/project-view/projectView.tsx
ui/src/components/project-view/style.scss
ui/src/components/project-view/warning.tsx
ui/src/components/telemetry/index.ts
ui/src/components/treenode/tree.tsx
ui/src/components/upload/component.tsx
ui/src/locales/cs/translation.json
ui/src/locales/de/translation.json
ui/src/locales/en/translation.json
ui/src/locales/es/translation.json
ui/src/locales/fr/translation.json
ui/src/locales/it/translation.json
ui/src/locales/pl/translation.json

- show a project when it is opened in the printer
- Change design apikey form
- show page error when HTTP digest has a problem

Oneclik extension

---

spec/openapi.yaml

Include:
/api 
/api/version
/api/hostname 
/api/files/preview
/api/before-confirm

Update OpenAPI Specification

---

spec/openapi.yaml

Include in job data:
- timeZone
- layerHeight
- exposureTimeCalibration

update job specification

---

ui/src/components/app.tsx

- fix updating telemetry with apikey
- update auth like Prusa Connect Local v 2.0.0

fix apikey update

---

src/printer/mini/dashboard.js
src/printer/sl1/dashboard.js
src/printer/sl1/job.js
templates/pages/dashboard.html

Dashboard Title:
**Printer status: Idle / Printing**
Dashboard temperatures label should be lower case

fix dashboard title and temperature title

---

src/printer/components/preview.js

Enable reload of preview data as exposure times and print duration
estimate might change.

Reload details of preview

---

src/printer/sl1/exposure.js

- minimum is set same as step to 100 ms

fix: Expo calibration increment time step and limit

---

src/locales/source/en.json
templates/components/modal/welcome.html

Fix welcome text to be printer model neutral

---

src/printer/components/upload.js

Quickfix to show sl1s files on all SL1[x] printers. SL1SW-1421

Show .sl1s in file upload

---

CHANGELOG.md
package-lock.json
src/index.js
src/locales/source/cs.json
src/locales/source/en.json
src/printer/components/errors.js
src/printer/components/settings.js
src/printer/components/settingsActions.js
src/printer/components/upload/direct.js
templates/pages/settings.html
tools/server/miscellaneous.js
tools/server/printer.js
tools/server/settings.js

* Add serial number setting
* Add initial 0% to upload process (to be shown even before printer responds)
* Prevent api polling when previous requests were not handled
* Prevent error messages flood in case of a connection problem

Add serial number setting

---

CHANGELOG.md
config.sl1.js
package-lock.json
package.json
scripts/remote_install.sh
src/index.js
src/printer/components/dataFormat.js
src/printer/components/errors.js
src/printer/components/job.js
src/printer/components/projects.js
src/printer/components/toast.js
src/printer/components/upload/direct.js
src/printer/components/upload/index.js
src/printer/fdm/dashboard.js
src/printer/fdm/index.js
src/printer/sla/dashboard.js
src/printer/sla/index.js
src/styles.css
templates/components/job/props.html
templates/components/telemetry.html
tools/server/mock/fdm.js
tools/server/mock/printer.js
tools/server/mock/sla.js
webpack.config.js

This PR will:
* Update error handling to avoid duplicates of popups
* Fix remote upload for SL1
* Fix inversed cover state for SL1
* Add FE version output to console log
Solves SL1SW-1546

Adapt changes for SLA printers

---

src/index.js
src/printer/fdm/index.js
src/printer/sla/index.js

* If one call fails for some reason, others will be handled
* Connection state will be handled by response from `/api/printer` endpoint

Fix polling promises error handling

---

src/printer/components/projects.js

fix: SLA: rename USB source

---

CHANGELOG.md
config.mini.js
package-lock.json
package.json
src/auth.js
src/printer/components/settings/logs.js
src/printer/fdm/index.js
src/printer/sla/index.js
src/styles.css
templates/components/job/buttons.html
templates/components/preview.html
templates/components/title_default.html
webpack.config.js

* Hide print button on MINI
* Fix logs displaying
* Fix word wrapping and breaking in logs
* Fix modal dialog z-index
* Fix printing image preview and progress responsiveness
* Add optional name and location to page heading

Next UI improvements

---

templates/components/temperature_graph_fdm.html
templates/components/temperature_graph_sla.html

Fix telemetry graph labels visibility

---

src/locales/source/cs.json
src/locales/source/en.json
src/printer/components/files.js
src/printer/components/storage.js
src/printer/components/upload/index.js
src/printer/components/upload/remote.js
templates/components/upload.html

- Hide upload widget when `sdcard` storage is selected
- Handle upload request and upload process separately

Update upload widget

---

src/printer/components/job.js

- Solves temporarily compatibility between different printers

Add fallback file path generation for job data

---

src/printer/components/settings.js

Change CONNECT status handling

---

src/locales/source/cs.json
src/locales/source/en.json
src/printer/components/temperature_graph.js
src/printer/components/upload/remote.js
src/styles.css
templates/components/job/progress.html
templates/components/node/current_folder.html
templates/components/node/storage.html
templates/components/temperature_graph_fdm.html
templates/components/title_default.html
templates/components/upload.html
templates/components/upload/direct.html
templates/components/upload/remote.html
templates/pages/control.html
templates/pages/dashboard.html
templates/pages/files.html
templates/pages/settings.html

1. Unify font sizes
2. Change layout on dashboard
3. Update FDM svg telemetry

Apply layout changes to dashboard page

---

src/printer/common.js
src/printer/fdm/index.js
src/printer/sla/index.js

Unify printer label

---

src/printer/components/files.js
src/printer/fdm/index.js
src/printer/sla/index.js
src/styles.css
templates/components/node/storage.html
templates/components/title_default.html

- Show `Storage` instead of path in page title

Change storage page title

---

src/printer/components/files.js
src/printer/components/jobActions.js
src/printer/components/upload/confirm.js
src/printer/components/upload/direct.js
src/printer/components/upload/index.js
src/printer/components/upload/remote.js
src/printer/fdm/dashboard.js
src/printer/sla/dashboard.js

- Adds confirm dialog on `Start printing after upload` checkboxes
- Disables checkbox when printing

Attach confirm dialog to start after upload checkbox

---

src/styles.css
templates/pages/control.html

Add more options to extruder controls

---

config.mini.js

So enable it in the configuration.

Mini now supports starting print remotely

---

src/printer/components/files.js

1. Folders first
2. Updated files first
3. Alphabetical order

Add sorting of files on the front end side

---

templates/components/telemetry.html
webpack.config.js

Config:
```
WITH_TELEMETRY_NOZZLE_DIAMETER: false,
WITH_TELEMETRY_MATERIAL: false,
```

Make nozzle diameter and material configurable

---

src/index.js
webpack.config.js

This will help to track what FE is installed on specific printer.

Add commit hash to version log output

---

src/printer/components/settings/logs.js

Fix error message about big log files downloading

---

src/locales/c.json
src/locales/source/cs.json
src/locales/source/de.json
src/locales/source/en.json
src/locales/source/es.json
src/locales/source/fr.json
src/locales/source/it.json
src/locales/source/kr.json
src/locales/source/pl.json
src/printer/components/job.js
src/styles.css
templates/components/job.html
templates/components/job/buttons.html

Split close and stop print buttons for job and file preview

---

src/printer/components/control.js
templates/pages/control.html

Allow temperature, speed and flow control when printing

---

src/printer/components/fileActions.js
src/printer/components/job.js
src/printer/components/jobActions.js
src/printer/components/upload/confirm.js

This is not an expected fix, but still good for safety. For the expected behavior we need some explicit method to find out when command execution had finished.

Disable dialog buttons on interaction

---

src/styles.css

- use same color for overlay as the page background
Fixes: SL1SW-1637 https://dev.prusa3d.com/browse/SL1SW-1637

css: loading-overlay: change the backgroud color

---

config.mini.js
src/auth.js
src/helpers/button.js
src/printer/components/fileActions.js
src/printer/components/files.js
src/printer/components/job.js
webpack.config.js

This PR:
- Adds configuration parameter for API KEY based authentication (DIGEST is default)
- Adds raw download functionality for DIGEST authentication
- Adds spinner and disabling to download buttons

Transparent file downloading

---

src/locales/source/cs.json
src/locales/source/de.json
src/locales/source/en.json
src/locales/source/es.json
src/locales/source/fr.json
src/locales/source/it.json
src/locales/source/pl.json
src/printer/sla/exposure.js
src/styles.css
templates/components/job/buttons.html
templates/components/preview.html

- previously applied in 441c2fec bu overwriten by 084f6136
Fixes: SL1SW-1635

SLA: locales: Reapply correct naming of "Print settings"

---

config.mini.js

Digest authentication works, so we need to update config.

New config for mini.

---

src/printer/components/files.js
templates/components/node/current_folder.html
templates/components/node/up_folder.html

Fix current path in file browser

---

src/printer/components/camera.js

* Remove filtering of cameras by status
* Add camera name and status to image `alt` text

Change behavior of non-connected cameras

---

config.mini.js
src/printer/components/files.js
templates/components/node/current_folder.html
webpack.config.js

- [Fix files sorting in subfolders](https://github.com/prusa3d/Prusa-Link-Web/commit/8e735bf2f220cbc9460d80f04d343393f388b13d)
- [Add configuration parameter for files sorting by name only](https://github.com/prusa3d/Prusa-Link-Web/commit/ae615a46f2a4dbffad221b44271c08b04cc67a95) with `WITH_NAME_SORTING_ONLY`

Update files sorting

---

src/printer/components/dropdown/index.js
src/styles.css

- Handle Escape
- Handle Up/Down arrow buttons
- Handle Enter
- Improve auto close
- Add max-height + scroll
- Add highlight of the active option

Improve UX of the dropdown component

---

src/printer/components/cameras.js

* [Fix camera CONNECT link state displaying](https://github.com/prusa3d/Prusa-Link-Web/pull/307/commits/aca07ea93b9d493e6f8a6f64adc48fa6c34b74da)
* [Do not allow to perfrom fix connection attempt if camera is not detected](https://github.com/prusa3d/Prusa-Link-Web/pull/307/commits/3827b301cf66584345b60bf1eef9629faac74e2e)

Fix camera states handling

---

src/printer/components/settings.js

This is dependent on the appropriate change in [Prusa-Link](https://github.com/prusa3d/Prusa-Link/pull/594)
Make sure you have up to date BE before testing.

Add current user name value to settings

---

src/printer/components/settings.js

@tomashusakk  here is the fix for error pop-up on settings opening

Fix API call to system versions

---

src/printer/fdm/dashboard.js

This should solve your console warnings during navigation between pages

Improve cameras code safety during navigation

---

tools/server/mock/errors.js

Hotfixed error message

---

src/printer/components/cameras.js
src/printer/components/job.js
src/printer/fdm/dashboard.js
templates/pages/dashboard.html

This PR
- removes cameras previews from dashboard
- fixes bug with missing preview if switch between dashboard and cameras

Leave one camera on dashboard

---

src/printer/common.js
src/printer/fdm/dashboard.js
src/printer/fdm/index.js
src/printer/sla/dashboard.js
src/printer/sla/index.js
src/router.js

Add printer status to document title

---

src/assets/file-icon.svg
src/assets/m1/file-icon.svg
src/printer/components/files.js
templates/components/node/file.html

Add regular file icon

---

src/printer/components/upload/remote.js

Add error handling for invalid download URLs

---

src/locales/c.json
src/locales/source/cs.json
src/locales/source/de.json
src/locales/source/en.json
src/locales/source/es.json
src/locales/source/fr.json
src/locales/source/it.json
src/locales/source/kr.json
src/locales/source/lt.json
src/locales/source/nl.json
src/locales/source/pl.json
src/locales/source/sk.json
src/printer/components/storage.js

Fix storage free space indicator

---

templates/components/node/current_folder.html

Closes https://github.com/prusa3d/Prusa-Link/issues/723

Cancel uppercase for current folder component

---

src/printer/components/files.js
src/printer/components/job.js
src/printer/fdm/context.js

This PR:
1. reflects appropriate change on BE,
2. solves issue with enabled delete button for SD card files.

Add support for read_only property

---

src/locales/c.json
src/locales/source/cs.json
src/locales/source/de.json
src/locales/source/en.json
src/locales/source/es.json
src/locales/source/fr.json
src/locales/source/it.json
src/locales/source/kr.json
src/locales/source/lt.json
src/locales/source/nl.json
src/locales/source/pl.json
src/locales/source/sk.json
src/printer/components/cameras.js
src/styles.css
templates/components/modal/camera-settings.html

Add simple camera focus control if supported

---

src/helpers/upload_request.js
src/locales/c.json
src/locales/source/cs.json
src/locales/source/de.json
src/locales/source/en.json
src/locales/source/es.json
src/locales/source/fr.json
src/locales/source/it.json
src/locales/source/kr.json
src/locales/source/lt.json
src/locales/source/nl.json
src/locales/source/pl.json
src/locales/source/sk.json
src/printer/components/upload/confirm.js
src/printer/components/upload/direct.js
src/styles.css

Add confirmation modal to overwrite a file by upload

---

src/printer/components/updateProperties.js
src/styles.css
templates/components/telemetry.html

Target Temperatures not set:
Target Temperatures have been set:

Hide zero temperatures in telemetry

---

config.mini.js
src/helpers/upload_request.js
tools/server/mock/fdm.js

Add .bgcode support

---

spec/openapi.yaml

This PR corrects the spelling of `ATTENTION` in the `StatusPrinter` schema. 
While implementing a notification system that checks the status of my printer using the API I noticed that one of the statuses were misspelled.   
The code was able to be built and ran locally.
It did generate errors in the web console which I suspect is unrelated:
```javascript
[Warning] Handle error – {code: 404, eTag: null, data: {title: "Error 404", message: "Not Found"}} (main.c11cf35ba578f5d7d0db.js, line 6126)
```

Correct typo of ATTENTION in status enumeration

---

tools/loaders/shared.js
tools/server/miscellaneous.js
tools/server/printer.js
tools/server/settings.js

fix(typo): correct typos in comments
